#!/bin/bash
#--# All lines that start with this combination will be deleted on production commandd
if [ ! -f data ]; then
    echo "¿Desea crear un nuevo repositoio? si/no"
    read createRepo
    if [ "$createRepo" = "si" ]; then 
        touch data
        chmod 700 data
        echo "Se ha creado satisfactoriamente un fichero de almacenaje"
    fi
fi    

exitProgram=0

while [ $exitProgram = 0 ]; do
    echo -e "1. Agregar nueva entrada\n2.Buscar una entrada\n3. Salir"
    read option

    if [ "$option" = 3 ]; then
        exitProgram="0"        
    fi 

    entryName=""
    entryValue=""

    # Registering a new registry
    if [ "$option" -eq 1 ]; then 
        echo "Indique un nombre para su registro: "
        read entryName
        echo "Indique el valor que desea almacenar: "
        read entryValue
        echo "Esta Ud. de acuerdo en registrar la entrada $entryName con valor $entryValue ? y/n"
        read entryConfirmation
        
        if [ "$entryConfirmation" = "y" ]; then
            echo -e $entryName'\t'$entryValue | awk 'BEGIN{FS="\t"}{print toupper($1)FS$2}' >> data
            echo $command
            exitProgram=0
        fi
        
    fi 

    # Search for a Specific registry
    if [ "$option" -eq 2 ]; then
        echo "¿Que desea buscar?: "
        read needle 
        if [ "$needle" != "" ]; then
            #--# Lets try to pass to awk an already uppered needle
            uneedle=$(echo $needle | awk '{print toupper($0)}')
            #--#echo $uneedle 
            awk -v needle=$uneedle 'BEGIN{}$1~needle{print $1"\t"$2}' data
        fi        
    fi

    if [ "$option" -lt 3 ]; then
        echo "¿Desea realizar otra operación? y/n"
        read anotherOperation
        if [ "$anotherOperation" = "n" ]; then
            exitProgram="1"
        fi
    fi
    if [ "$option" -eq 3 ]; then
        exit 0
    fi
done   
exit 0 
